//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcja.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sara, dodaj komendę.
        /// </summary>
        public static string AddNewCommand {
            get {
                return ResourceManager.GetString("AddNewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiedz, jeżeli będziesz mnie potrzebował.
        /// </summary>
        public static string AskIfYouNeed {
            get {
                return ResourceManager.GetString("AskIfYouNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komenda została dodana.
        /// </summary>
        public static string CommandHasBeenAdded {
            get {
                return ResourceManager.GetString("CommandHasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CommndsFilePath {
            get {
                return ResourceManager.GetString("CommndsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy wykonać tą operację?.
        /// </summary>
        public static string ConfirmOperation {
            get {
                return ResourceManager.GetString("ConfirmOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka katalogu.
        /// </summary>
        public static string DirectoryPath {
            get {
                return ResourceManager.GetString("DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BŁĄD.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka pliku.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formularz jest już uruchomiony.
        /// </summary>
        public static string FormIsAlreadyOpen {
            get {
                return ResourceManager.GetString("FormIsAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operację anulowano.
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka programu.
        /// </summary>
        public static string ProgramPath {
            get {
                return ResourceManager.GetString("ProgramPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Należy uzupełnić wymagane pola!.
        /// </summary>
        public static string RequiredFieldNotFill {
            get {
                return ResourceManager.GetString("RequiredFieldNotFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cześć, jestem Sara. W czym mogę pomóc?.
        /// </summary>
        public static string SaraIntroduce {
            get {
                return ResourceManager.GetString("SaraIntroduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sara, jesteś potrzebna.
        /// </summary>
        public static string SaraIsNeeded {
            get {
                return ResourceManager.GetString("SaraIsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas zapisu danych:.
        /// </summary>
        public static string SaveDataError {
            get {
                return ResourceManager.GetString("SaveDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sara, pokaż komendy.
        /// </summary>
        public static string ShowCommands {
            get {
                return ResourceManager.GetString("ShowCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj komendę.
        /// </summary>
        public static string SysTrayAddCommand {
            get {
                return ResourceManager.GetString("SysTrayAddCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string SysTrayCloseApplication {
            get {
                return ResourceManager.GetString("SysTrayCloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz Sarę.
        /// </summary>
        public static string SysTrayDisableRecognizer {
            get {
                return ResourceManager.GetString("SysTrayDisableRecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włącz Sarę.
        /// </summary>
        public static string SysTrayEnableRecognizer {
            get {
                return ResourceManager.GetString("SysTrayEnableRecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż komendy.
        /// </summary>
        public static string SysTrayShowCommands {
            get {
                return ResourceManager.GetString("SysTrayShowCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracja.
        /// </summary>
        public static string SysTrayShowConfig {
            get {
                return ResourceManager.GetString("SysTrayShowConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sara, czas na przerwę.
        /// </summary>
        public static string TimeForBreak {
            get {
                return ResourceManager.GetString("TimeForBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres strony.
        /// </summary>
        public static string URLAddress {
            get {
                return ResourceManager.GetString("URLAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co mogę dla Ciebie zrobić?.
        /// </summary>
        public static string WhatCanDo {
            get {
                return ResourceManager.GetString("WhatCanDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
